language: python
sudo: false
cache: pip
language: python
env:
  global:
    - SKGGM_VERSION=a0ed406586c4364ea3297a658f415e13b5cbdaf8
matrix:
  include:
  - name: "Pytest python 3.5 without skggm"
    python: "3.5"
    before_install:
      - sudo apt-get install liblapack-dev
      - pip install --upgrade pip "pytest<5"
      - pip install wheel cython numpy scipy codecov pytest-cov scikit-learn
    script:
      - pytest test --cov;
    after_success:
      - bash <(curl -s https://codecov.io/bash)
  - name: "Pytest python 3.6 with skggm"
    python: "3.6"
    before_install:
      - sudo apt-get install liblapack-dev
      - pip install --upgrade pip pytest
      - pip install wheel cython numpy scipy codecov pytest-cov scikit-learn
      - pip install git+https://github.com/skggm/skggm.git@${SKGGM_VERSION};
    script:
      - pytest test --cov;
    after_success:
      - bash <(curl -s https://codecov.io/bash)
  - name: "Pytest python 3.7 with skggm"
    python: "3.7"
    before_install:
      - sudo apt-get install liblapack-dev
      - pip install --upgrade pip pytest
      - pip install wheel cython numpy scipy codecov pytest-cov scikit-learn
      - pip install git+https://github.com/skggm/skggm.git@${SKGGM_VERSION};
    script:
      - pytest test --cov;
    after_success:
      - bash <(curl -s https://codecov.io/bash)
  - name: "Syntax checking with flake8"
    python: "3.7"
    before_install:
      - pip install flake8
    script:
      - flake8 --extend-ignore=E111,E114 --show-source;
      # Use this instead to have a syntax check only on the diff:
      # - source ./build_tools/travis/flake8_diff.sh;
branches:
  only:
  - master
