language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.6"
before_install:
  - pip install --upgrade pip
  - pip install wheel
  - pip install numpy scipy scikit-learn
  - if [[ $TRAVIS_PYTHON_VERSION -ge 3.6 ]]; then pip install skggm; fi
script: pytest test
