language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get install liblapack-dev
  - pip install --upgrade pip pytest
  - pip install wheel cython numpy scipy codecov pytest-cov scikit-learn flake8
  - if [[ ($TRAVIS_PYTHON_VERSION == "3.6") ||
          ($TRAVIS_PYTHON_VERSION == "3.7") ||
          ($TRAVIS_PYTHON_VERSION == "2.7") ]]; then
              pip install git+https://github.com/skggm/skggm.git@a0ed406586c4364ea3297a658f415e13b5cbdaf8;
    fi
script:
  # we run flake8 to ensure syntax (no need to run it on every version)
  - if [[ $TRAVIS_PYTHON_VERSION == "3.7" ]];
      then flake8 --ignore=E111,E114,W504;
    fi
  # we do coverage for all versions so that codecov will merge them: this
  # way we will see that both paths (with or without skggm) are tested
  - pytest test --cov;
after_success:
  - bash <(curl -s https://codecov.io/bash)

