language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.4"
before_install:
  - pip install --upgrade pip pytest
  - pip install wheel
  - pip install codecov
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]];
    then pip install pytest-cov;
    fi
  - pip install numpy scipy scikit-learn
script:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]];
    then pytest test --cov;
    else pytest test;
    fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
