language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.6"
before_install:
  - sudo apt-get install liblapack-dev
  - pip install --upgrade pip
  - pip install wheel
  - pip install cython numpy scipy scikit-learn codecov
  - if [[ ($TRAVIS_PYTHON_VERSION == "3.6") ||
          ($TRAVIS_PYTHON_VERSION == "2.7")]]; then
              pip install git+https://github.com/skggm/skggm.git@a0ed406586c4364ea3297a658f415e13b5cbdaf8;
    fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]];
    then pip install pytest-cov pytest==3.6;
    fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]];
    then pytest test --cov;
    else pytest test;
    fi
after_success:
  - bash <(curl -s https://codecov.io/bash)

