language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.4"
before_install:
  - CODECOV_TOKEN="23c57533-8bcc-4caa-84e3-419854017212"
  - pip install --upgrade pip
  - pip install wheel
  - pip install codecov
  - if [[ $TRAVIS_PYTHON_VERSION == "3.6" ]];
    then pip install pytest-cov pytest==3.6;
    fi
  - pip install numpy scipy scikit-learn
script:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.6" ]];
    then pytest test --cov;
    else pytest test;
    fi
after_success:
  - codecov
